#! /usr/bin/sh

#set -x
dir=$1
Result=`ls -a $dir | sort`
declare -a ARRAYDOT
declare -a ARRAY
let countdot=0
let count=0
IFS=$'\n'
#echo "help"
for FILE in $Result #first create two arrays, 
	    #one of dots (to ensure priority) and one of normal sorted files
do
    if [ ! -r "$dir/$FILE" ]
    then
	echo "Read permission not granted for file: $dir/$FILE"
	continue #continue to next file
     fi
    if [ ! -L "$dir/$FILE" ]  #if not a symbolic link
    then
	if [ -f "$dir/$FILE" ] #if a regular file
         then
	  #  echo "$dir/$FILE is a regular file."

	    if [ ${FILE:0:1} = '.' ] #if dot first, add to dot array
	     then
		ARRAYDOT[$countdot]="$dir/$FILE"
		let countdot=countdot+1
	    else #add to normal array
		ARRAY[$count]="$dir/$FILE"
		let count=count+1
	     fi
	fi
    fi
done

#then add all items from normal array into dot array

for i in "${ARRAY[@]}"
do
 #   echo $i
    ARRAYDOT[$countdot]=$i #put all indexes in the second array into the first
    let countdot=countdot+1
done

#for i in "${ARRAYDOT[@]}"
#do
 #     echo "$i is the first"
#done
#test each file with the ones before it, if it finds a match,
#then make that file form a hardlink to the one in front

let i=0 #outer
let j=0 #inner
#echo "$countdot is total files"
while [ $i -lt $countdot ]
do

    let j=0
    while [ $j -lt $i ]
    do
	#echo "inner=$j outer=$i"
	#echo "Comparing ${ARRAYDOT[$i]} ${ARRAYDOT[$j]}"
	cmp -s "${ARRAYDOT[$i]}" "${ARRAYDOT[$j]}"
	var=$?
	#echo $var !!!!!
	if [ $var -eq 0 ] #check result of cmp, if same, hardlink them, else, skip
	then
	    temp=${ARRAYDOT[$i]} 
	    rm ${ARRAYDOT[$i]}
	    ln ${ARRAYDOT[$j]} $temp
	   # echo "Hardlinked $temp to ${ARRAYDOT[$j]}"
	    break
	fi
	let j=j+1
    done

    let i=i+1
done



		
		

	    
    
